using UnityEngine;

/// <summary>
/// Adds a large, invisible physical floor under the player at startup.
/// This acts as a rescue for broken ProBuilder mesh colliders that
/// lost their collision data, preventing the player from falling through the world.
/// </summary>
public class FloorRescue : MonoBehaviour
{
    [Tooltip("How far below the player's spawn point to place the floor.")]
    [SerializeField] private float floorOffset = 1.0f;

    [Tooltip("The size of the invisible floor X/Z dimensions.")]
    [SerializeField] private float floorSize = 1000f;

    private void Start()
    {
        // Create an empty GameObject for the floor
        GameObject safetyFloor = new GameObject("SafetyFloor_AutoGenerated");
        
        // Position it just below the player's initial position
        safetyFloor.transform.position = new Vector3(
            transform.position.x, 
            transform.position.y - floorOffset, 
            transform.position.z
        );

        // Add a BoxCollider
        BoxCollider boxCollider = safetyFloor.AddComponent<BoxCollider>();
        boxCollider.size = new Vector3(floorSize, 1f, floorSize);

        // Remove the visual renderer (it's just an empty GameObject, so it's already invisible)
        
        // Set the layer to Default so the player can walk on it
        safetyFloor.layer = 0; 

        // Parent it to root so it doesn't move with the player
        safetyFloor.transform.SetParent(null);
    }
}
